# Generated by Django 5.2.4 on 2026-07-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calories',
            field=models.FloatField(blank=True, null=True, verbose_name='칼로리 정보(Kcal)'),
        ),
        migrations.AddField(
            model_name='post',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True, verbose_name='탄수화물(g)'),
        ),
        migrations.AddField(
            model_name='post',
            name='fat',
            field=models.FloatField(blank=True, null=True, verbose_name='지방(g)'),
        ),
        migrations.AddField(
            model_name='post',
            name='nutrition_image',
            field=models.ImageField(blank=True, upload_to='nutrition/%Y%m%d', verbose_name='영양성분 이미지'),
        ),
        migrations.AddField(
            model_name='post',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name='단백질(g)'),
        ),
    ]
